### ISSUE TITLE
[Bug] The new pose is not being used 

### ISSUE THREAD

**Issue by jygkh** [nonnonstop/sd-webui-3d-open-pose-editor#106]
**Describe the bug**
After clicking send to txt2img, the pose appears in the single image box, but the pose has no affect on the generated image
**To Reproduce**
1. clicking send to txt2img
2. Check "enable"
3. Generate image

**Expected behavior**
The generated images are supposed to use the pose, the last image is supposed to be the pose itself
**Screenshots**
![Screenshot (2356)](https://github.com/nonnonstop/sd-webui-3d-open-pose-editor/assets/57826173/88993d04-68bf-483f-96a8-44aa9c0fa3b2)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - A1111 WebUI Version: version: [1.6.0]
 - Extension Version: f2d5aac5 | 2023-04-15 09:21:06
 - ControlNet Version: feea1f65	2023-12-08 13:34:52

**Comment by troodpart** [comment]
You don't appear to have any ControlNet models selected in your example. With a pose loaded from this extension, preprocessor should be set to none. But model should be set to openpose. Try that and see if it fixes your issue:

![image](https://github.com/nonnonstop/sd-webui-3d-open-pose-editor/assets/142268494/dcde4053-0822-4d93-ae4b-16e0434c8695)

Models can be found here: https://github.com/Mikubill/sd-webui-controlnet#download-models
