### ISSUE TITLE
3D viewport doesn't load and no buttons work

### ISSUE THREAD

**Issue by sitrec** [nonnonstop/sd-webui-3d-open-pose-editor#11]
I just installed this extension and the viewport is just white and it doesn't seem like any of the buttons do anything. I haven't had any problems with other extensions. The viewport in PoseX works fine.

I installed with the "Install from URL" tab in Automatic1111. 
Did I miss something?

Thanks!

**Comment by rinaldop** [comment]
The same for me.

**Comment by nonnonstop** [comment]
try updating webui

**Comment by rinaldop** [comment]
Updated! White screen yet.

**Comment by rinaldop** [comment]
I am using phyton 3.10.10

**Comment by nonnonstop** [comment]
ok, give me the console log from chrome dev tool

**Comment by nonnonstop** [comment]
See https://support.shortpoint.com/support/solutions/articles/1000222881-save-browser-console-file

**Comment by DarkJukeMastah** [comment]
I seem to be having the same issue as well. The UI itself is there, but the viewport does not seem to load.
I'm using firefox, these are the logs I get when I navigate to the 3d openpose tab and press a button.

<details><summary>Log</summary>
<p>

0 0 openpose.mjs:20826:104
0 0 openpose.mjs:20826:206
WebGL warning: drawArraysInstanced: Drawing to a destination rect smaller than the viewport rect. (This warning will only be given once)
Infinity% loaded 2 openpose.mjs:17928:17
Object { isObject3D: true, uuid: "1514b3bd-20df-4451-9f0a-1a9fdde070bc", name: "", type: "Group", parent: null, children: (2) […], up: {…}, position: {…}, rotation: {…}, quaternion: {…}, … }
openpose.mjs:18173:11
Array [ {…}, {…} ]
openpose.mjs:18175:41
Uncaught (in promise) TypeError: xt.data is undefined
    st index.4395ab38.js:76
    promise callback*At/</</< index.4395ab38.js:76
    le index.4395ab38.js:4
    le index.4395ab38.js:4
    b Checkbox.svelte:14
    Vn index.4395ab38.js:4
    Vn index.4395ab38.js:4
    f Checkbox.svelte:17
    u Checkbox.svelte:27
index.4395ab38.js:76:2720


</p>
</details>

**Comment by TeutonJon78** [comment]
Mine behaves the same  as @DarkJukeMastah -- UI shows up, but no viewport. The buttons do things like open dialogs. I tired it Firefox and Chrome, so I don't think it's a browser issue.

The only difference from normal is I'm using the DirectML branch of A1111 since I run AMD, which tends to run a few commits behind the main A1111 repo. Perhaps there's something different between the branches that's preventing it? I also updated to Python 3.10.10 over 3.10.6.

**Comment by DarkJukeMastah** [comment]
I have the latest webui and 3d openpose, so I don't think versions are the issue...
I'm pretty sure it worked before I did an update though, so something changed since one of the extension updates that borked it.
I'll try getting an earlier version to see if it works.

**Comment by TeutonJon78** [comment]
I just tried "safe mode" by turning off other extensions and this one ended up loading correctly. It seems to be a conflict with the updated Latent Couple extension that's preventing it from loading the UI.

I'm using the one that multi-region aware -- https://github.com/ashen-sensored/stable-diffusion-webui-two-shot

If I disable it, the viewport starts correctly. If it's enabled, the posing viewport doesn't get started.

**Comment by DarkJukeMastah** [comment]
You're right, when I disabled the two-shot extension the viewport showed up for me as well.

**Comment by nonnonstop** [comment]
Thank you! Fixed!

**Comment by FFOvO** [comment]
![1679080945592](https://user-images.githubusercontent.com/128182197/226000143-71ae4064-c25c-42b1-abdc-84da15a76237.jpg)
VM1503:3 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'makeImages')
    at eval (eval at <anonymous> (index.4395ab38.js:75:2081), <anonymous>:3:43)
    at index.4395ab38.js:34:32410
    at HTMLButtonElement.<anonymous> (index.4395ab38.js:76:2455)
    at index.4395ab38.js:4:1266
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.le (index.4395ab38.js:4:1253)
    at HTMLButtonElement._ (Button.svelte:10:48)
    at index.4395ab38.js:4:1266
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.le (index.4395ab38.js:4:1253)

**Comment by nonnonstop** [comment]
@FFOvO Try updating webui

**Comment by ZhUyU1997** [comment]
> @FFOvO Try updating webui

I think you can try to be compatible with the legacy version as it can't detect *.mjs but can detect *.js

**Comment by nonnonstop** [comment]
> I think you can try to be compatible with the legacy version as it can't detect *.mjs but can detect *.js

You are right. I'm updated now.

**Comment by FFOvO** [comment]
> > 我认为您可以尝试与旧版本兼容，因为它无法检测到*.mjs，但可以检测*.js
> 
> 你是对的。我现在更新了。

Thank you for your efforts. Installing the latest version of the plugin in the extension has solved my problem.
