### ISSUE TITLE
all great but pose library and ability to extract a pose from upoading photo

### ISSUE THREAD

**Issue by 2blackbar** [nonnonstop/sd-webui-3d-open-pose-editor#12]
OR at least upload an image with openpose skeleton sticks and it would try to match it in 3d view, its so cumbersome to move skeleton around and hands are literally impossible to get right, so a library for hand poses would help a lot
Separate lib for hands and separate for poses
Also default focal should be 100mm , SD isnt great with perspective

**Comment by ZhUyU1997** [comment]
Already supported it on the online version (https://github.com/ZhUyU1997/open-pose-editor), later should support it on this extension

**Comment by nonnonstop** [comment]
@ZhUyU1997 Thank you! I will try to merge soon.

**Comment by ZhUyU1997** [comment]
@nonnonstop it imports mediapipe pose AI models and so large size. you can consider it put it on project or run it using python.

**Comment by nonnonstop** [comment]
Merged. I'll consider migrating to python later.
