### ISSUE TITLE
bones width is too big 

### ISSUE THREAD

**Issue by 2blackbar** [nonnonstop/sd-webui-3d-open-pose-editor#13]
You should have option to use sticks as bones cause theyre too large when you do head close up and openpose wont recognize skeleton at all on close up of head, try it
Bones should be that thin
![image](https://user-images.githubusercontent.com/33694664/225806266-a44c02cd-0800-499d-8ce6-3e7941e17e26.png)

**Comment by ZhUyU1997** [comment]
I will add a parameter to control it

**Comment by nothings** [comment]
This is not a real fix. This requires me to change many bones' thickness if I change the view, e.g. if I'm generating several views orbiting around a figure this is a crazy amount of work.

You can just convert the endpoints of each bone from 3D to 2D, then draw the bone in 2D with a fixed thickness, that way it will always produce the correct 2D result that OpenPose is expecting. That way it will work every time, at any scale, at any zoom, from any direction, without any user intervention.
