### ISSUE TITLE
no skeleton 

### ISSUE THREAD

**Issue by Mukyung-Kim** [nonnonstop/sd-webui-3d-open-pose-editor#14]
![Screenshot_20230317-214352_Chrome](https://user-images.githubusercontent.com/77491818/225908402-b43220cb-dccb-4d73-a352-b349a814dd4c.jpg)

**Comment by nonnonstop** [comment]
Are there error messages in the output of webui launch command or in the browser's developer tools console?
See [this link](https://support.shortpoint.com/support/solutions/articles/1000222881-save-browser-console-file) to save logs from dev tools.

**Comment by victorvalenzuela** [comment]
Same problem here

**Comment by nonnonstop** [comment]
@victorvalenzuela Same as #28? Try clearing your browser cache and reloading.

**Comment by Mukyung-Kim** [comment]
ValueError: File cannot be fetched: /content/drive/MyDrive/SD/extensions/sd-webui-3d-open-pose-editor/style.css. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.

------------------------------------------------

tunnel : ngrok

**Comment by Mukyung-Kim** [comment]
ValueError: File cannot be fetched: /content/drive/MyDrive/SD/extensions/sd-webui-3d-open-pose-editor/style.css. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.

tunnel : ngrok
