### ISSUE TITLE
Requeset UI change

### ISSUE THREAD

**Issue by ZhUyU1997** [nonnonstop/sd-webui-3d-open-pose-editor#19]
The editor is more and more complex.
If only provide webui bind by some buttons is not enough, and need to make many changes upstream.
I request to reduce some buttons and use the interaction of the editor self.

**Comment by nonnonstop** [comment]
Like this?

![image1](https://user-images.githubusercontent.com/42905588/226497807-61397833-1e7f-417a-bd29-9c89358a30d0.png)
![image2](https://user-images.githubusercontent.com/42905588/226497840-74d7a551-44d6-4d4d-9bd2-bb79496e40d4.png)

**Comment by nonnonstop** [comment]
I'll push this changes by tomorrow

**Comment by nonnonstop** [comment]
Merged

**Comment by ZhUyU1997** [comment]
I realize that the difference in UI is already very small. I will add some modes to vite later, which can detect extension or online at compile time, which can further reduce code differences. Anyway, thanks for your work.
