### ISSUE TITLE
Great work, how about merge to my project？

### ISSUE THREAD

**Issue by ZhUyU1997** [nonnonstop/sd-webui-3d-open-pose-editor#2]

**Comment by nonnonstop** [comment]
I'm not going to pull request because of the large differences from yours. (even got rid of the online feature...)

However, I would be very happy if you could be a collaborator for this repository. I just sent you an invite to be a collaborator, so commit as you wish if you're interested.

**Comment by ZhUyU1997** [comment]
Thanks for your invitation, Can I put your project link on civitai site?

**Comment by nonnonstop** [comment]
Of course. Thank you!
