### ISSUE TITLE
Ui Bug

### ISSUE THREAD

**Issue by Gollum0002** [nonnonstop/sd-webui-3d-open-pose-editor#20]
The 3d open pose editor is white or blank in opera gx, the extension is working properly on chrome

![Screenshot (73)](https://user-images.githubusercontent.com/109045152/226304585-1538ab5d-a22a-4caf-9b57-cfbf884804dd.png)

This possibly has something to do with the issue

**Comment by kasimok** [comment]
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/5194603/226891426-80f55026-4143-4b15-8b2e-56e59e940913.png">
Same on safari of macOS, the online version looks OK

**Comment by kasimok** [comment]
> <img alt="image" width="1791" src="https://user-images.githubusercontent.com/5194603/226891426-80f55026-4143-4b15-8b2e-56e59e940913.png">
> 
> Same on safari of macOS, the online version looks OK

Update: reinstall fixed the problem.
