### ISSUE TITLE
Unable to use the "Send to..." buttons

### ISSUE THREAD

**Issue by bigboss97** [nonnonstop/sd-webui-3d-open-pose-editor#23]
I've installed the extension. The Edit Openpose tab works fine. After clicking on the Create button it switches to the Send to ControlNet tab. I can see the four images are populated. But when I click on those two Send buttons nothing happens. I've tried it on Chrome and Firefox.

What have I done wrong?

**Comment by nonnonstop** [comment]
@bigboss97 
Are there error messages in the output of webui launch command or in the browser's developer tools console?
See [this link](https://support.shortpoint.com/support/solutions/articles/1000222881-save-browser-console-file) to save logs from dev tools.

**Comment by bigboss97** [comment]
Thanks for the response. Somehow it's working beautifully today.

I had this issue for few weeks already. From time to time I tried again with no luck and couldn't find similar issue on net.
Few days ago I updated the extension which didn't help. Last night I tried again and still not working. Then I decided to post my question and now it's working. That's weird  :-)
Thanks anyway.

**Comment by Sostay** [comment]
我也有这个问题，在colab上使用没有问题，但是本地点击发送无论如何都没有反应，试了很久，也升级到最新版了 还是一样的问题。命令窗口也没有任何错误提示~

**Comment by Sostay** [comment]
![image](https://user-images.githubusercontent.com/6897274/227529403-1f48252d-0548-4425-9e1d-7468c9004d36.png)

**Comment by Sostay** [comment]
> @Sostay Thank you for reporting! What is the version of ControlNet? The version is displayed on the Extensions tab of WebUI. ![image](https://user-images.githubusercontent.com/42905588/227536695-7107b0a7-2a0f-4039-9304-49c7913963b6.png)
> 
> That error is that the ControlNet's image upload box is not found. I don't know why.

fc8a8855 (Mon Feb 27 10:32:23 2023)

**Comment by Sostay** [comment]
> @Sostay Could you update ControlNet to `7377d499 (Wed Mar 1 13:06:26 2023)` or later?

I don't know how to update to the archived version, but I manually updated to the latest version of ControlNet, and the issue of failed sending still exists.
![image](https://user-images.githubusercontent.com/6897274/227567067-1738dc5c-76c2-4d60-a015-b42da58770be.png)

**Comment by nonnonstop** [comment]
@Sostay restarted webui? if you still have problem, let me know what version of control net again.

**Comment by Sostay** [comment]
> 7377d499 (Wed Mar 1 13:06:26 2023)

241c05f  Mar 23, 2023

**Comment by nonnonstop** [comment]
@Sostay Thanks. Please execute the following 3 commands in the browser console and tell me the output.
```javascript
gradioApp().querySelectorAll("#txt2img_script_container")
gradioApp().querySelectorAll("#controlnet")
gradioApp().querySelector("#txt2img_script_container #controlnet")
```
![image](https://user-images.githubusercontent.com/42905588/227702449-a1ba2fc1-dccc-4dcc-b30e-426c98a13068.png)

**Comment by Sostay** [comment]
> @Sostay Thanks. Please 执行 the following 3 commands in the browser console and tell me the output.
> 
> ```js
> gradioApp().querySelectorAll("#txt2img_script_container")
> gradioApp().querySelectorAll("#controlnet")
> gradioApp().querySelector("#txt2img_script_container #controlnet")
> ```
> 
> ![image](https://user-images.githubusercontent.com/42905588/227702449-a1ba2fc1-dccc-4dcc-b30e-426c98a13068.png)

![image](https://user-images.githubusercontent.com/6897274/227702965-4754439b-f6d6-4611-bc01-6fbd8b73109e.png)

**Comment by nonnonstop** [comment]
@Sostay Thank you.
If possible, please save the log file and send it to me. Right-click on the browser console to save the log.

![image](https://user-images.githubusercontent.com/42905588/227704259-6cf1c20c-7177-4645-8d25-b9b343e1f447.png)

**Comment by Sostay** [comment]
[127.0.0.1-1679730353662.log](https://github.com/nonnonstop/sd-webui-3d-open-pose-editor/files/11068324/127.0.0.1-1679730353662.log)
[127.0.0.1-1679730341213.log](https://github.com/nonnonstop/sd-webui-3d-open-pose-editor/files/11068325/127.0.0.1-1679730341213.log)
[127.0.0.1-1679730318599.log](https://github.com/nonnonstop/sd-webui-3d-open-pose-editor/files/11068326/127.0.0.1-1679730318599.log)

**Comment by nonnonstop** [comment]
@Sostay Sorry, I wrote that wrong! 🥺
Could you press Ctrl+S in WebUI to save the HTML file and send it to me?

**Comment by Sostay** [comment]
> @Sostay Sorry, I wrote that wrong! 🥺 Could you press Ctrl+S in WebUI to save the HTML file and send it to me?

[Stable Diffusion.zip](https://github.com/nonnonstop/sd-webui-3d-open-pose-editor/files/11069056/Stable.Diffusion.zip)

**Comment by nonnonstop** [comment]
@Sostay Thank you! I just updated this extension. It now supports the old ControlNet (fc8a8855), so give it a try.

**Comment by Sostay** [comment]
> @Sostay Thank you! I just updated this extension. It now supports the old ControlNet (fc8a8855), so give it a try.

I also reinstall the ControlNet，howerver，it works now~ thank you！
