### ISSUE TITLE
[feature request] Detect pose from image

### ISSUE THREAD

**Issue by psykokwak-com** [nonnonstop/sd-webui-3d-open-pose-editor#24]
Hi all,
It could be great to have the "detect pose from image" feature as we have in https://zhuyu1997.github.io/open-pose-editor/
It will allow us to "import" a pose from an image (as we can do on ControlNet) but we can edit the pose in 3D directly in the editor.

**Comment by nonnonstop** [comment]
Please update this extension.

**Comment by psykokwak-com** [comment]
great! Thank you :)
