### ISSUE TITLE
You forgot to add the body center point

### ISSUE THREAD

**Issue by bosbrand** [nonnonstop/sd-webui-3d-open-pose-editor#26]
Original open pose has a body center point which allows you to rotate the entire body relative to the ground plane. Also I can't work around it, because I can't rotate the camera around it's z axis.

**Comment by nonnonstop** [comment]
I don't understand what you are talking about, please tell me the details.
Do you mean that no circles for rotation display at the body center?
![image](https://user-images.githubusercontent.com/42905588/227762553-c6d0156d-1d52-4d71-8a9b-4565c436ea84.png)

**Comment by nonnonstop** [comment]
Reopen if the problem still remains.
