### ISSUE TITLE
error on clean install

### ISSUE THREAD

**Issue by vladmandic** [nonnonstop/sd-webui-3d-open-pose-editor#3]
clean install of the extension results in:

    RuntimeError: File at path extensions/sd-webui-3d-open-pose-editor/models/shou.jpg does not exist.

looking at the files, it seems to be referenced by `models/hand.fbx` model so model loader is failing.

**Comment by KurozumiGH** [comment]
I also get the same error.

**Comment by nonnonstop** [comment]
Me too. 😢 
You can ignore it, but I'll fix it later.

**Comment by nonnonstop** [comment]
ZhUyU1997 fixed it in #6
