### ISSUE TITLE
512x512 is saved as 640x640

### ISSUE THREAD

**Issue by bigboss97** [nonnonstop/sd-webui-3d-open-pose-editor#39]
The default settings width/height= 512. After creating the pose, I clicked on Download. The image is saved as 640x640.

**Comment by nonnonstop** [comment]
Works for me.
Please tell me the version and steps to reproduce.

**Comment by bigboss97** [comment]
99f3e80d (Tue Mar 28 11:58:16 2023)

**Comment by bigboss97** [comment]
Verified on 8453fbb2 (Wed Apr 5 15:27:34 2023), no longer an issue.
