### ISSUE TITLE
Add background image doesn't work

### ISSUE THREAD

**Issue by Aghneel** [nonnonstop/sd-webui-3d-open-pose-editor#4]

**Comment by nonnonstop** [comment]
Try updating webui.
If it still doesn't work, give me the details.

**Comment by Aghneel** [comment]
Can't load a background for some reason but the skeleton works fine and send it to controlnet is working too!

**Comment by Aghneel** [comment]
I have this error when trying to load a background, i'm on firefox in case : 
![image](https://user-images.githubusercontent.com/41067116/225361075-ced5d54c-8c27-49f6-a3dd-362cc22299a4.png)

**Comment by nonnonstop** [comment]
Thank you for reporting.
Please update this extension to the latest version.

**Comment by Aghneel** [comment]
Fixed it, thanks!
