### ISSUE TITLE
'Move mode' issue

### ISSUE THREAD

**Issue by ostap667inbox** [nonnonstop/sd-webui-3d-open-pose-editor#40]
[99f3e80](https://github.com/nonnonstop/sd-webui-3d-open-pose-editor/commit/99f3e80d06501bb1b42394dbe52fa6bb997ca800)
When I press X or select 'Move mode' in the menu, the active node changes to the center node, common to the entire model. It is not possible to switch to other nodes.
![chrome_we6XlqDKhQ](https://user-images.githubusercontent.com/123593542/229271234-81413ccf-12cd-4f4c-8786-0fcbd7d23f9b.png)

**Comment by ZhUyU1997** [comment]
You should open ”Free Mode”

**Comment by ostap667inbox** [comment]
> You should open ”Free Mode”

Thanks. It work
