### ISSUE TITLE
Add scene doesn't work

### ISSUE THREAD

**Issue by Aghneel** [nonnonstop/sd-webui-3d-open-pose-editor#5]

**Comment by Aghneel** [comment]
Thanks for the answer, skeleton appears but delayed like 5 sec later. 
I also have this error, probably related?  
```raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path C:\stable-diffusion-vtest\stable-diffusion-webui\extensions\sd-webui-3d-open-pose-editor\models\shou.jpg does not exist.
```

**Comment by nonnonstop** [comment]
Yes, it takes a few seconds to display the skeleton. It is not a bug.
RuntimeError is another issue (#3), but it won't happen if you update this extension.

**Comment by Aghneel** [comment]
Works now, thank you!
