### ISSUE TITLE
colab Error, hand.fbx does not exist. 

### ISSUE THREAD

**Issue by gootalok** [nonnonstop/sd-webui-3d-open-pose-editor#7]
### maybe hand.gbx. The file path seems to be incorrect. please help.

> ERROR:    Exception in ASGI application

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/starlette/responses.py", line 335, in __call__
>     stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
>   File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
>     return await future
>   File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
>     result = context.run(func, *args)
> FileNotFoundError: [Errno 2] No such file or directory: '/content/repository/extensions/sd-webui-3d-open-pose-editor/models/hand.fbx'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
>     result = await app(  # type: ignore[func-returns-value]
>   File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
>     return await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 273, in __call__
>     await super().__call__(scope, receive, send)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 122, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 184, in __call__
>     raise exc
>   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 162, in __call__
>     await self.app(scope, receive, _send)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/gzip.py", line 24, in __call__
>     await responder(scope, receive, send)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/gzip.py", line 44, in __call__
>     await self.app(scope, receive, self.send_with_gzip)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
>     raise exc
>   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
>     await self.app(scope, receive, sender)
>   File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
>     raise e
>   File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 718, in __call__
>     await route.handle(scope, receive, send)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 276, in handle
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 69, in app
>     await response(scope, receive, send)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/responses.py", line 338, in __call__
>     raise RuntimeError(f"File at path {self.path} does not exist.")
> RuntimeError: File at path /content/repository/extensions/sd-webui-3d-open-pose-editor/models/hand.fbx does not exist.

**Comment by nonnonstop** [comment]
When you installed the extension, did you change the directory name to something other than "sd-webui-3d-open-pose-editor"?
Renaming directory of extension is not yet supported.

![image](https://user-images.githubusercontent.com/42905588/225512196-edebbe52-d49c-4aaf-9ec4-d3b7c0a2d44d.png)

**Comment by gootalok** [comment]
At first, I tried installing it by extracting the zip file, and then I installed it by downloading it from git after deleting it.
But, It isn't work also.

**Comment by nonnonstop** [comment]
I have never used Colab. 🤔 

Show me the file list in "/content/repository/extensions/"
```
!ls /content/repository/extensions/
```

**Comment by gootalok** [comment]
only txt file, because colab use /content/Drive/MyDrive/SD/extentions/

**Comment by nonnonstop** [comment]
@gootalok 
Fixed. But it might be an error depending on the path. If it still doesn't work, please let me know the error message.
